### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by medwatt** [marohnicluka/giac#1]
Hello,
I came to find this page through my search for a program that can do continuous Fourier Transform on the HP Prime calculator. The calculator uses a subset of XCas/Giac for is CAS. I was excited when I realized that you had implemented Fourier Transform for the Xcas and I tried it on the windows application and it worked just as expected.

I contact the HP development team and asked if they could add fourier and ifourier to the Prime. As I already mentioned, not all XCas functions make their way to the Prime. I was told that they could not add fourier and ifourier due to the way you licensed your code and the fact that the Prime's OS is not open source. They told me the only way they can include those two functions (and possibly some of the others that you've coded) is for you to change your licensing to allow your code to be used in a commercial product like the prime. So, I'm here hoping that you can somehow be persuaded to change your licensing and allow the Prime team to add your implementation of FT to the prime. I'm studying electrical engineering and having the ability to do FT, convolution, correlation, etc, on the calculator is massive. I'm sure many others would be appreciative if you could allow your code to be used on the Prime.

Thanks.

**Comment by marohnicluka** [comment]
Hello,
thank you for your interest and sorry for a delayed response. I could indeed distribute my code under a dual license which would be suitable for inclusion in Prime CAS source tree. I'm all for it if that helps students and teachers. I'll contact the HP representatives and try to make an arrangement.
